<a href="https://colab.research.google.com/github/Devesh946/AI_df20555/blob/main/Lab4/my_recommender_movie.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import operator

In [21]:
df0 = pd.ExcelFile('https://github.com/albanda/CE888/blob/master/lab4-recommender/movies_latent_factors.xlsx?raw=true')

In [35]:
df0.sheet_names

['Items', 'Users']

In [36]:
df_Items = pd.read_excel('https://github.com/albanda/CE888/blob/master/lab4-recommender/movies_latent_factors.xlsx?raw=true',sheet_name='Items',index_col=None)

In [37]:
df_Items.head()

Movie ID  ...  Factor15
0        11  ... -0.248806
1        12  ...  1.274993
2        13  ... -0.419092
3        14  ... -0.681191
4        22  ... -2.292566

[5 rows x 17 columns]

In [38]:
df_Users = pd.read_excel('https://github.com/albanda/CE888/blob/master/lab4-recommender/movies_latent_factors.xlsx?raw=true',sheet_name='Users', index_col=None)

In [39]:
df_Users.head()

User   Factor1   Factor2   Factor3  ...  Factor12  Factor13  Factor14  Factor15
0  4768 -0.204024  0.161079 -0.090447  ...  0.355404  0.007108 -0.118663 -0.039125
1   156 -0.189652 -0.178979 -0.091490  ... -0.048606  0.045916  0.113671  0.179873
2  5323 -0.115308 -0.090886 -0.053129  ... -0.019460  0.108372  0.054471 -0.109552
3   174 -0.227462 -0.272532 -0.017231  ... -0.082396  0.036767 -0.165438  0.050692
4  4529 -0.014616 -0.102218 -0.107935  ... -0.132836 -0.039897  0.129063  0.102669

[5 rows x 16 columns]

In [40]:
df_Users.shape, df_Items.shape

((25, 16), (100, 17))

In [55]:
# Which 3 movies would you recommend to User 786?
num_factors = df_Users.shape[1]-1
user_pref = df_Users[df_Users['User'] == 786].iloc[:, -num_factors:].values[0]
item_feat = df_Items.iloc[:, -num_factors:].values
user_pref

array([-0.12176269,  0.01106521, -0.03712125,  0.03256778,  0.01757049,
        0.09580188,  0.12023804, -0.04840965,  0.00882947,  0.121778  ,
        0.09378259,  0.04475409, -0.00308681,  0.16448667, -0.07523082])

In [29]:
#df_Items[df_Items['Movie ID']==788].index.values[0]

63

In [19]:
#user with ID 2092 will give to the movie with ID 155
df = df_Items.iloc[list(pd.DataFrame(preference).index)]
#item_feat=df_Items.iloc[[68], -num_factors:].values
item_feat

array([[ 2.26314166, -0.06776079, -0.20546291,  0.06888043, -0.18909006,
         2.07855412,  2.44492228, -0.07597149, -0.6747668 , -0.19855978,
         1.64137998, -0.83927648, -0.51708595, -1.05843134, -0.93174606]])

In [43]:
preference = item_feat.dot(user_pref)

In [44]:
round(preference[0],2)
df_Users.columns[1:]
preference

array([ 0.1474981 ,  0.06983066,  0.05034643,  0.10362144,  0.43445992,
       -0.349929  ,  0.10881859,  0.02706829,  0.14355296,  0.24107678,
        0.19533595,  0.22597099,  0.25323484, -0.14367942,  0.48778482,
        0.40695203,  0.47629982, -0.06796637, -0.00346879, -0.09780667,
        0.04007909,  0.23928014,  0.41468031, -0.10614675,  0.03911447,
        0.09716218, -0.08133268,  0.46989755, -0.03139847, -0.39115697,
       -0.08712855,  0.13940897,  0.003168  ,  0.23871336,  0.1941581 ,
       -0.00431458, -0.3496473 , -0.67048872,  0.08852994,  0.17133532,
       -0.12681625,  0.56277095, -1.14692595, -1.32254628, -0.13783104,
       -0.09532403,  0.13444858, -0.31405841, -0.32126222, -0.06166568,
        0.3863941 , -0.32259049,  0.23892751,  0.21541377,  0.21051028,
        0.03894228, -0.24252431, -0.420186  , -0.36430616,  0.43727051,
       -0.13250326, -0.05173059, -0.13352892, -0.05891093,  0.08372632,
        0.36607193,  0.13892302,  0.1063737 ,  0.21083979,  0.01

In [45]:
pd.DataFrame(preference).head(20)

0
0   0.147498
1   0.069831
2   0.050346
3   0.103621
4   0.434460
5  -0.349929
6   0.108819
7   0.027068
8   0.143553
9   0.241077
10  0.195336
11  0.225971
12  0.253235
13 -0.143679
14  0.487785
15  0.406952
16  0.476300
17 -0.067966
18 -0.003469
19 -0.097807

In [46]:
top_values = pd.DataFrame(preference).nlargest(3, 0)
top_indices = top_values.index
list(top_indices)

[41, 14, 16]

In [47]:
df_Items.iloc[list(top_indices)]

Movie ID  ...  Factor15
41       550  ... -0.724341
14       120  ... -0.276280
16       122  ... -0.314937

[3 rows x 17 columns]

In [56]:
#quiz Q5
##Factor9 for the movie with ID=9802
#df_Items.head()
df_Fator = df_Items[['Movie ID','Factor9']]

value = df_Fator[df_Fator['Movie ID']==9802]['Factor9'].values[0]

round(value,3)

0.396

In [33]:
#quiz Q6
#with the lowest loading of factor 4

df_factor4 = df_Items[['Movie ID','Factor4']]
df_factor4.sort_values('Factor4')

Movie ID   Factor4
51       604 -2.255945
72       955 -1.732132
5         24 -1.686559
71       954 -1.627068
36       393 -1.624796
..       ...       ...
65       808  2.286099
1         12  2.443297
91      8587  2.532220
70       862  2.539259
96     10020  2.579640

[100 rows x 2 columns]